### ISSUE TITLE
[Feature][Binder] 라벨 생성/수정/삭제 조건 추가

### ISSUE THREAD

**Issue by soojiinleee** [soojiinleee/MyDailyLabel#17]
## 기능 개선
- 이미 등록된 이름으로 라벨 등록 불가(유저의 등록된 라벨 리스트 중)
- 노트에 등록된 라벨 이름 수정 시 관련 노트에 라벨 이름 모두 수정
- 라벨 삭제 시 관련된 노트 모두 삭제

## To-do
- [x] 라벨 중복 등록 불가
- [x] 라벨 수정 시 노트에 등록된 라벨 이름 수정
- [x] 라벨 삭제 시 등록된 노트 모두 삭제

**Comment by soojiinleee** [comment]
- 라벨 수정 시 노트에 등록된 라벨 이름 수정 -> foreignkey로 연결 되어 있어서 별도 수정 필요 없음
- model.cascade로 설정 되어 있어서 완료
